### ISSUE TITLE
System.FormatException when using HubSpotContactClient.ListAsync for models with a DateTime

### ISSUE THREAD

**Issue by Karl2893782** [skarpdev/dotnetcore-hubspot-client#78]
When running the following code:
```
var customers = await
                        _hubSpotApi.ListAsync<ContactListHubSpotEntity<HubspotCustomer>>(new ContactListRequestOptions
                        {
                            ContactOffset = offset,
                            NumberOfContactsToReturn = _hubspotConfig.BatchSize,
                            PropertiesToInclude = _propertiesToInclude
                        });
```

I get the following exception:

```
System.FormatException
String '1594252800000' was not recognized as a valid DateTime  

  at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value, IFormatProvider provider)
   at System.String.System.IConvertible.ToDateTime(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Skarp.HubSpotClient.Core.Requests.RequestDataConverter.ConvertSingleEntity(ExpandoObject dynamicObject, Object dto)
   at Skarp.HubSpotClient.Core.Requests.RequestDataConverter.FromHubSpotListResponse[T](ExpandoObject dynamicObject)
   at Skarp.HubSpotClient.Core.Requests.RequestSerializer.DeserializeListEntity[T](String json)
   at Skarp.HubSpotClient.Core.HubSpotBaseClient.<ListAsync>b__11_0[T](String responseData)
   at Skarp.HubSpotClient.Core.HubSpotBaseClient.<SendRequestAsync>d__17`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Skarp.HubSpotClient.Core.HubSpotBaseClient.<ListAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Skarp.HubSpotClient.Contact.HubSpotContactClient.<ListAsync>d__7`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyProject.HubSpotService.<DownloadCustomers>d__9.MoveNext()
```

My HubspotCustomer class has a DateTime property.
The issue seems to be that the hubspot client is not parsing the returned date correctly.

**Comment by nover** [comment]
Hi @Karl2893782 

Thanks for reporting the issue - the trick here is that `'1594252800000'` is _not_ a datetime format that dotnet recognizes natively, it's a unix timestamp and requires "special parsing".

The easiest thing for you to do is the following:

```
class HubspotCustomer
{
[DataMember("theTimestampField")]
public string Timestamp {get; set;}

public DateTimeOffset DateTime => DateTimeOffset.FromUnixTimeSeconds(Convert.ToInt64(DateTimeOffset.FromUnixTimeSeconds));
}
```

Now I haven't run the above code through a compiler, but it should be close enough to a solution you can work from (I hope) 🤞

**Comment by LeeStevens318** [comment]
Yeah i've come across this before, i used to just handle it after the fact, but looking quickly we could do something like:
In the `RequestDataConverter.ConvertSingleEntity`
```
if (targetProp != null)
{
	// skip any nullable properties with a empty value
	if (Nullable.GetUnderlyingType(targetProp.PropertyType) != null && string.IsNullOrEmpty(dynamicValue.ToString()))
		continue;

	// convert DateTime?
	if (targetProp.PropertyType == typeof(DateTime?) && long.TryParse(dynamicValue.ToString(), out var milliseconds))
	{
		var unixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
		var dateTime = unixEpoch.AddMilliseconds(milliseconds);

		dynamicValue = dateTime;
	}
}
```

Example:
```
public class ExtendContactHubSpotEntity : ContactHubSpotEntity
{
	[DataMember(Name = "lastmodifieddate")]
	public DateTime? LastModified { get; set; }
}
```

Outcome:
![image](https://user-images.githubusercontent.com/28816427/118900269-dad8d680-b953-11eb-8570-b988e5e4cfc7.png)

**Comment by nover** [comment]
Looks awesome @LeeStevens318 - we should probably also support `DateTime` and `DateTimeOffset`/`DateTimeOffset?` too.

**Comment by LeeStevens318** [comment]
@nover Yep no worries, i'll have a look

**Comment by LeeStevens318** [comment]
@Karl2893782 v0.20.0 has been pushed.
